name: Mostrar data e hora do push
on:
  push:
    branches: [ main ]

jobs:
  datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir data/hora do runner
        run: |
          echo "Runner date/time: $(date --iso-8601=seconds)"
          if [ -n "${{ github.event.head_commit.timestamp }}" ]; then
            echo "Timestamp do commit (github.event.head_commit.timestamp): ${{ github.event.head_commit.timestamp }}"
          fi
