name: Estatísticas por commits do push
on:
  push:
    branches: [ main ]

jobs:
  sequence-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir data e usuário
        run: |
          echo "Data (runner): $(date --iso-8601=seconds)"
          echo "Pusher: $GITHUB_ACTOR"
          echo "Ref: $GITHUB_REF"

      - name: Contar arquivos HTML/CSS/JS por commit
        run: |
          echo "Iterando pelos commits do push..."
          FILES_JSON=$(cat "$GITHUB_EVENT_PATH" | jq -c '.commits[] | {added: .added, modified: .modified}')
          TOTAL_HTML=0
          TOTAL_CSS=0
          TOTAL_JS=0
          i=0
          echo "$FILES_JSON" | while read commit; do
            i=$((i+1))
            HTML=$(echo "$commit" | jq '[.added[], .modified[]] | map(select(test("\\.html$"; "i"))) | length')
            CSS=$(echo "$commit" | jq '[.added[], .modified[]] | map(select(test("\\.css$"; "i"))) | length')
            JS=$(echo "$commit" | jq '[.added[], .modified[]] | map(select(test("\\.js$"; "i"))) | length')
            TOTAL_HTML=$((TOTAL_HTML + HTML))
            TOTAL_CSS=$((TOTAL_CSS + CSS))
            TOTAL_JS=$((TOTAL_JS + JS))
            echo "Commit $i -> html:$HTML css:$CSS js:$JS"
          done
          echo "Totais sequenciais: html=$TOTAL_HTML css=$TOTAL_CSS js=$TOTAL_JS"
