name: Estatísticas agregadas do push
on:
  push:
    branches: [ main ]

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Contar arquivos HTML/CSS/JS agregados
        run: |
          # Captura todos os arquivos adicionados ou modificados em todos os commits
          FILES=$(jq -r '[.commits[].added? // [], .commits[].modified? // []] | flatten | .[]' "$GITHUB_EVENT_PATH" || echo "")

          # Contagens seguras mesmo que FILES esteja vazio
          HTML=$(echo "$FILES" | grep -i '\.html$' || true | wc -l | tr -d ' ')
          CSS=$(echo "$FILES" | grep -i '\.css$' || true | wc -l | tr -d ' ')
          JS=$(echo "$FILES" | grep -i '\.js$' || true | wc -l | tr -d ' ')

          echo "Arquivos agregados no push -> html: $HTML, css: $CSS, js: $JS"
