name: Estatísticas por commits do push
on:
  push:
    branches: [ main ]

jobs:
  sequence-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir data e usuário
        run: |
          echo "Data (runner): $(date --iso-8601=seconds)"
          echo "Pusher: $GITHUB_ACTOR"
          echo "Ref: $GITHUB_REF"

      - name: Contar arquivos HTML/CSS/JS por commit
        run: |
          TOTAL_HTML=0
          TOTAL_CSS=0
          TOTAL_JS=0
          NUM_COMMITS=$(jq '.commits | length' "$GITHUB_EVENT_PATH")

          for i in $(seq 0 $((NUM_COMMITS-1))); do
            # Pega os arquivos adicionados/modificados do commit atual, sem quebrar se não existir
            FILES=$(jq -r ".commits[$i].added? // [] | .[] , .commits[$i].modified? // [] | .[]" "$GITHUB_EVENT_PATH")

            HTML=$(echo "$FILES" | grep -i '\.html$' | wc -l | tr -d ' ')
            CSS=$(echo "$FILES" | grep -i '\.css$' | wc -l | tr -d ' ')
            JS=$(echo "$FILES" | grep -i '\.js$' | wc -l | tr -d ' ')

            TOTAL_HTML=$((TOTAL_HTML + HTML))
            TOTAL_CSS=$((TOTAL_CSS + CSS))
            TOTAL_JS=$((TOTAL_JS + JS))

            echo "Commit $((i+1)) -> html:$HTML css:$CSS js:$JS"
          done

          echo "Totais sequenciais: html=$TOTAL_HTML css=$TOTAL_CSS js=$TOTAL_JS"
